= Shear Force Team Code

== TODO List

- [ ] Improve slide limit logic and rotator slide arm logic to ensure always pass inspection
- [ ] Get the Urchin to work
- [ ] Improve Auto Right to deliver at least 2 specimens to the high bar and park
- [ ] Reassess and test all servo/arm position numbers with the Urchin installed
- [ ] Improve Auto Left to score level-1 hang again
- [ ] Improve Auto Left to put at least 1 sample into the high basket
- [ ] Experiment with different box/urchin orientations for intake from the floor
- [ ] Create routine in Geronimo that uses the Limelight to report Red, Blue, or Yellow --- AKSHAY
- [ ] Create routine in Geronimo that uses the Limelight to report left or right inches from specimen
- [ ] Fully Re-Calibrate Geronimo
- [ ] Fix the bad laptop to build again (probably uninstall/reinstall android studio)
- [ ] Create routine in Geronimo that uses color sensor to report red, blue, or yellow --- MATTHEW
- [x] Find servo and arm positions to put specimen into so can just drive forward to snap onto high bar
- [x] Experiment with high specimen delivery using backwards arm position
- [x] Test slide limit logic
- [x] Test and fix issues with intake star not being reliable
- [x] Create updated auto routines that puts specimen on bar, and then moves the 3 floor samples to corner, then parks --- AIDAN
- [x] Create slide limit in horizontal position to pass inspection
- [x] Add slide limit touch sensor logic
- [x] Split up Slide motor control logic to run independently, so motors can catch up
- [x] Split up Slide Arm Rotator motor control logic to run independently, so motors can catch up
- [x] Improve arm control so the arm doesn't slam down when set to position 0.
- [x] Create control methods to lift specimen off wall and to pull down on bar
- [x] Test & Document best arm intake positions for different common actions (intake from floor, deliver to high/low basket, pick up specimen off wall, deliver specimen to high/low)
- [x] Test on Geronimo an auto trajectory that uses arm actions in parallel while driving
- [x] Test new manual control combo buttons
- [x] Test all 4 auto park routines
- [x] Create auto routines to park from all 4 start locations
- [x] Test Manual control - adjust game-controller controls to be easy to use
- [x] Test using trajectory
- [x] Create routine in Geronimo that returns X, Y distance to an object --- AIDAN
- [x] Create autonomous to put specimen on bar AIDAN & SHREY
- [x] Create Test op mode for testing the 4 arm motors and limit switches --- CLAIRE
- [x] Add Comments to Four Arm Motors Limit Switch Class CLAIRE


