= Shear Force Team Code

== TODO List

- [ ] Calibrate Geronimo GIANNA & CLAIRE
- [ ] Test Manual control - adjust game-controller controls to be easy to use
- [ ] Test & Document best arm intake positions for different common actions (intake from floor, deliver to high/low basket, pick up specimen off wall, deliver specimen to high/low)
- [ ] Create & TEST ON GERONIMO auto routines to park from all 4 start locations
- [ ] Test using trajectory
- [ ] Test on Geronimo an auto trajectory that uses arm actions while driving
- [ ] Create routine in Geronimo that uses the Limelight to report Red, Blue, or Yellow --- AKSHAY
- [ ] Create routine in Geronimo that uses color sensor to report red, blue, or yellow --- MATTHEW
- [X]  Create routine in Geronimo that returns X, Y distance to an object --- AIDAN
- [X] Create autonomous to put specimen on bar AIDAN & SHREY
- [X] Create Test op mode for testing the 4 arm motors and limit switches --- CLAIRE
- [X] Add Comments to Four Arm Motors Limit Switch Class CLAIRE
- [ ] Improve class so the arm doesn't slam down when y is released. CLAIRE & GIANNA


