= Shear Force Team Code

== TODO List

---

- [ ] Create Programming section of Judging presentation
- [ ] Claire: Create a special button (or two) to use for inspections
- [ ] Aidan: Test and get Auto Left delivering at least 3 samples to high basket
- [ ] Speed up Hang routines
- [ ] Speed up basket delivery routines in Teleop (and then Auto)
- [ ] Change Auto routines to have better start positions (left start in box 2, right - start on a line instead of middle)
- [ ] Determine if there are swiper actions needed in more places of our autonomous routines
- [ ] Experiment again with using urchin to grab from specimen wall and hanging on high bar
- [ ] Akshay: Test Limelight on Geronimo for aligning on wall specimens
- [ ] Akshay: Create routine in Geronimo that uses the Limelight to report Red, Blue, or Yellow -- Prove on SummerChassis
- [ ] Fully Re-Calibrate Geronimo
- [ ] Claire: Experiment with PID control for rotator arms
- [ ] Aidan: Make a NEW Auto Right that does at least 4 specimens (deliver, try grabbing samples with urchin to speed up, deliver, deliver, deliver)
- [ ] Make a NEW auto left to put at least 4 samples into the high basket
- [ ] Create TeleOp Auto drive routines using roadrunner to get to basket and wall spot

---
- [x] experiment with other positions to see if can get urchin more reliable for intake
- [x] experiment with using urchin to push blocks away from the target urchin
- [x] Change end-game buzzer to be like 35 seconds
- [x] Portfolio: Claire: write paragraph about Arm Control Iterations going from single servo/motor control to complicated combination controls.  Why did we need to do this, what has it achieved, etc...?
- [x] Portfolio: Aidan: write paragraph about Autonomous Iterations -- discuss strategic reasons we focused on high specimen delivery over basket delivery first, and why we switched from forward delivery to reverse delivery, and why we flipped the specimen upside down
- [x] Portfolio: Aidan: write paragraph about how we use Roadrunner and MeepMeep Visualization for autonomous
- [x] Portfolio: Matt: write short paragraph about how we use color sensors, what iterations and lessons learned did we go through on getting them to work?
- [x] Portfolio: Akshay: write paragraph about what we have learned about the Limelight, be sure to cover different experiments and lessons learned about it
- [x] Portfolio: Claire: write short paragraph about currently learning about PID control for more precise arm motor control
- [x] Portfolio: Claire: write short paragraph about learning about PlantUML diagramming and how we used it to plan out our initial programming tasks
- [x] Portfolio: Matt: Sensors List: write a couple of sentences about how we use each of our sensors: IMU, Color Sensor, Touch Sensors, Odometry Pods
- [x] Akshay: Create routine in Geronimo that uses the Limelight to report left or right inches from specimen -- Prove on SummerChassis
- [x] Aidan: Make a NEW Auto Left to put at least 1 sample into the high basket
- [x] Shrey: Improve Driver Controls to be more preset oriented, move box rotation and hanger arm controls to multi-button (share + dpad left) to discourage their use and free up those buttons for other modes
- [x] Make sure all combo movements that move slides and rotator arms down, do slides first then arms, make sure all smooth
- [x] Update Basket delivery to be 2 push-buttons (step 1 raise arm rotators and set urchin position, step 2 raise slides to finish)
- [x] Aidan: Auto Right - Fix wall grab position to line up exactly on the seam
- [x] Gianna: Create driver control for swiper on Gamepad 1 and test it
- [x] Jared: teach Claire about using git branches
- [x] Gianna: Auto Right - Add swiper move as a parallel action after each grab / release action
- [x] Matt: Connect Blinkin to ColorRevV3Sensor() so that color shown is Red, Blue, yellow, or Green if nothing detected
- [x] Matt or Gianna: Configure Blinkin (expansion port 5) and Swiper (expansion port 4) servos
- [x] Matt: Turn on Blinkin logic again (note: only have 1 blinkin not 2)
- [x] Figure out if can reuse the wall or specimen high positions to start the climb (probably basket)
- [x] Create routine in Geronimo that uses color sensor to report red, blue, or yellow - AND sets the blinkin to right color --- MATTHEW
- [x] Improve slide limit logic and rotator slide arm logic to ensure always pass inspection
- [x] Improve the auto so the urchin moves after slides and arm rotator all down
- [x] Improve Auto Right to deliver at least 2 specimens to the high bar and park
- [x] Fix the bad laptop to build again (probably uninstall/reinstall android studio)
- [x] Experiment with different box/urchin orientations for intake from the floor
- [x] Get the Urchin to work
- [x] Reassess and test all servo/arm position numbers with the Urchin installed
- [x] Find servo and arm positions to put specimen into so can just drive forward to snap onto high bar
- [x] Experiment with high specimen delivery using backwards arm position
- [x] Test slide limit logic
- [x] Test and fix issues with intake star not being reliable
- [x] Create updated auto routines that puts specimen on bar, and then moves the 3 floor samples to corner, then parks --- AIDAN
- [x] Create slide limit in horizontal position to pass inspection
- [x] Add slide limit touch sensor logic
- [x] Split up Slide motor control logic to run independently, so motors can catch up
- [x] Split up Slide Arm Rotator motor control logic to run independently, so motors can catch up
- [x] Improve arm control so the arm doesn't slam down when set to position 0.
- [x] Create control methods to lift specimen off wall and to pull down on bar
- [x] Test & Document best arm intake positions for different common actions (intake from floor, deliver to high/low basket, pick up specimen off wall, deliver specimen to high/low)
- [x] Test on Geronimo an auto trajectory that uses arm actions in parallel while driving
- [x] Test new manual control combo buttons
- [x] Test all 4 auto park routines
- [x] Create auto routines to park from all 4 start locations
- [x] Test Manual control - adjust game-controller controls to be easy to use
- [x] Test using trajectory
- [x] Create routine in Geronimo that returns X, Y distance to an object --- AIDAN
- [x] Create autonomous to put specimen on bar AIDAN & SHREY
- [x] Create Test op mode for testing the 4 arm motors and limit switches --- CLAIRE
- [x] Add Comments to Four Arm Motors Limit Switch Class CLAIRE


