@startuml


package ControlHub #Tan {
  package Motors #LightGrey {
    [Motor0] -- [Motor1]
    [Motor1] -- [Motor2]
    [Motor2] -- [Motor3]
  }

  package Servos #LightGrey {
   [Servo-0] -- [Servo-1]
   [Servo-1] -- [Servo-2]
   [Servo-2] -- [Servo-3]
   [Servo-3] -- [Servo-4]
   [Servo-4] -- [Servo-5]
  }

  package Analog #LightGrey {
   [Analog_0_1] -- [Analog_2_3]
  }

  package Digital #LightGrey {
   [Digital_0_1] -- [Digital_2_3]
   [Digital_2_3] -- [Digital_4_5]
   [Digital_4_5] -- [Digital_6_7]
  }

  package I2C #LightGrey {
   [I2C_0] -- [I2C_1]
   [I2C_1] -- [I2C_2]
   [I2C_2] -- [I2C_3]

  }
}

package MotorNames #LightGreen {
  () "leftFront_leftOdometry" --> [Motor0] : 0
  () "rightFront_centerOdometry" --> [Motor1] : 1
  () "leftRear" --> [Motor2] : 2
  () "rightRear_rightOdometry" --> [Motor3] : 3
}

package ServoNames #Orange {
  () "clawServo" --> [Servo-0] : 0
  () "intakeRotater" --> [Servo-1] : 1
  () "intakeStar" --> [Servo-2] : 2
}

package DigitalNames #Pink {
  () "LimitSwitch-1" --> [Digital_0_1] : 0-1
  () "LimitSwitch-2" --> [Digital_2_3] : 2-3
  () "LimitSwitch-3" --> [Digital_4_5] : 4-5
  () "LimitSwitch-4" --> [Digital_6_7] : 6-7
}

package I2C_Names #LightBlue {
  () "ColorSensorLeft" --> [I2C_0] : 0
  () "ColorSensorRight" --> [I2C_1] : 1

}

@enduml